### PR TITLE
Hello-world: Files

### PR DESCRIPTION
**Pull request by Basir-Mohammadi**
**Hello-world Clone: Files**

**Add Lighthouse to improve the quality of web pages.**
**Add Webhint to improve your site's accessibility, speed, and cross-browser compatibility.**
**Add  Stylelint to avoid errors and enforce conventions in your styles.**

### CODE REVIEW

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @basirking , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ following the GitHub flow
✔️  Good implementing the h1 and color 

## Required Changes ♻️

- [ ]  Please make sure to use the right linters, try to remove Eslint linter, leave only linter for HTML and CSS 

- [ ] [OPTIONAL] you commits are not capitalized, I suggest next time to follow these[ rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to write a good commits  

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Basir-Mohammadi** [comment]
Hi @youmari 
please check this out and how to upload it to my dashboard?
thanks

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Basir-Mohammadi** [comment]
Hello, Yassine Omari
please check this out.
https://github.com/basirking/Hello-world2/pull/1

thanks

**Pull request merged**
